name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out'
        uses: actions/checkout@v4

      - name: 'Setup node js'
        uses: actions/setup-node@v4
        with:
          node-version: 20.x.x

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - name: Install Yarn Globally
        run: npm install -g yarn
      - name: Enable core pack for new yarn version
        run: core pack enable
      - name: Upgrade yarn to berry
        run: yarn set version berry
      - name: Install Dependencies
        run: yarn install
      - name: Run linting
        run: yarn run lint
      - name: Build
        run: yarn build
